services:
  acs-server:
    image: acs-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: acs-server
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
